volumes:
  etc_wireguard:

services:
  wg-easy:
    env_file: ./.env
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  hbbs:
    container_name: hbbs
    network_mode: "container:wg-easy"
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data_rustdesk:/root
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    network_mode: "container:wg-easy"
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data_rustdesk:/root
    depends_on:
      - wg-easy
    restart: unless-stopped